### PR TITLE
Dark theme

### PR DESCRIPTION
**Pull request by AetherPrior**
Add dark theme for site

### CODE REVIEW

**Comment by AetherPrior** [comment]
Preview Image:  
image

**Comment by agrawal-d** [comment]
This will make the entire website dark by default. It's not a good experience for a website to be dark-by default as its uncomfortable for some people and in some environments. If you can write some JavaScript code that allows toggling then it may be worth considering.

**Comment by AetherPrior** [comment]
You mean like a button for toggling? That would make sense yes. 
It could've been left open through I would've just committed to this :P

**Comment by agrawal-d** [comment]
There were a lot of unrelated changes coupled into this PR apart from the dark mode change.

**Pull request closed without merging**
